### ISSUE TITLE
Link to paper or results timing

### ISSUE THREAD

**Issue by pyrito** [Juelin-Liu/CliqueX#1]
Hi,

I'm trying to run this codebase with the example graph but I'm not sure how long it is supposed to take for maximal clique for the given dataset? Is there a paper linked to this project or some more documentation that can help me figure out what's going on? Thanks!

**Comment by juelinl** [comment]
Hello,

1) Unfortunately, none of the methods can finish in weeks. This is because there are too many maximal cliques in the given dataset. What can be compared is the relative mining rate of each method. (How many maximal cliques are discovered in each second.)

2) I started this project as an extension for a previous [paper](https://github.com/Juelin-Liu/CliqueX/blob/main/paper/LocalOnlineIndexing.pdf) which might be helpful.

3) In the high level, finding a graph pattern requires many set intersections. Traditionally, people would keep the two input sets sorted, and do a linear scan to compute the intersection. We discovered that we can represent the two sets in a bitmap format and use bitwise AND operation to compute the intersection. The trick is not to convert the entire graph into the bitmap format (which is known as the adjacency matrix) but only convert what is needed. You can find more details in the paper. Maximal clique is just a special case where we can use this trick.

**Comment by pyrito** [comment]
Thanks for getting back to me @Juelin-Liu. The linked paper was quite helpful. I'm trying to use the codebase to use it as a baseline for some of our research work.
